### ISSUE TITLE
Failed to pull image "openshift-istio-tech-preview/openshift-ansible:0.8.0"

### ISSUE THREAD

**Issue by scouturier** [maistra/openshift-ansible#84]
#### Description

Pod creation is failing with ImagePullBackOff with specific error: repository docker.io/openshift-istio-tech-preview/openshift-ansible not found for both Operator and System.

##### Version

Maistra 0.8.0
Openshift 3.11
RHEL 7.6

##### Steps To Reproduce
1. oc new-app -f https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.8/istio/istio_product_operator_template.yaml --param=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=<URL>
--

##### Observed Results
Pods are failing to create, getting the following error:

```
Failed to pull image "openshift-istio-tech-preview/openshift-ansible:0.8.0": rpc error: code = Unknown desc = repository docker.io/openshift-istio-tech-preview/openshift-ansible not found: does not exist or no pull access
```

**Comment by brian-avery** [comment]
Hi @scollier. How did you create this cluster? Did you use oc cluster up? If not, what does your cr.yaml look like?

**Comment by brian-avery** [comment]
Also, is this an OCP cluster or an OKD cluster?

**Comment by scouturier** [comment]
Hi Brian,

It's an OCP cluster running in Azure (if that matters)

I'm getting the error while creating the operator so I'll paste the both yaml for troubleshooting purpose.

Operator template: (identical from this project)

```
apiVersion: v1
kind: Template
metadata:
  name: istio-operator-job
parameters:
- displayName: Master Public URL
  description: The public URL for master
  name: OPENSHIFT_ISTIO_MASTER_PUBLIC_URL
  value: https://127.0.0.1:8443
- displayName: OpenShift Release
  description: The version of the OpenShift release.
  name: OPENSHIFT_RELEASE
  value: v3.11.0
  required: true
- displayName: Istio Operator Namespace
  description: The namespace for the Istio operator
  name: OPENSHIFT_ISTIO_OPERATOR_NAMESPACE
  value: istio-operator
  required: true
- displayName: Default Prefix
  description: The default image prefix for istio deployments
  name: OPENSHIFT_ISTIO_PREFIX
  value: openshift-istio-tech-preview/
- displayName: Default Version
  description: The default image version for istio deployments
  name: OPENSHIFT_ISTIO_VERSION
  value: 0.8.0
- displayName: Default Deployment Type
  description: The default deployment type for istio deployments
  name: OPENSHIFT_DEPLOYMENT_TYPE
  value: openshift
objects:
- kind: CustomResourceDefinition
  apiVersion: apiextensions.k8s.io/v1beta1
  metadata:
    name: installations.istio.openshift.com
  spec:
    group: istio.openshift.com
    names:
      kind: Installation
      plural: installations
      singular: installation
    scope: Namespaced
    version: v1alpha1
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: istio-operator
  rules:
  - apiGroups:
    - istio.openshift.com
    resources:
    - "*"
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    - securitycontextconstraints
    verbs:
    - "*"
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - "*"
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: default-account-istio-operator
  subjects:
  - kind: ServiceAccount
    namespace: ${OPENSHIFT_ISTIO_OPERATOR_NAMESPACE}
    name: default
  roleRef:
    kind: Role
    name: istio-operator
    apiGroup: rbac.authorization.k8s.io
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: default-account-istio-operator-cluster-role-binding
  subjects:
  - kind: ServiceAccount
    namespace: ${OPENSHIFT_ISTIO_OPERATOR_NAMESPACE}
    name: default
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: istio-operator
    namespace: ${OPENSHIFT_ISTIO_OPERATOR_NAMESPACE}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: istio-operator
    template:
      metadata:
        labels:
          name: istio-operator
      spec:
        containers:
          - name: istio-operator
            image: ${OPENSHIFT_ISTIO_PREFIX}istio-operator:${OPENSHIFT_ISTIO_VERSION}
            ports:
            - containerPort: 60000
              name: metrics
            command:
            - istio-operator
            args:
            - "--release=${OPENSHIFT_RELEASE}"
            - "--masterPublicURL=${OPENSHIFT_ISTIO_MASTER_PUBLIC_URL}"
            - "--istioPrefix=${OPENSHIFT_ISTIO_PREFIX}"
            - "--istioVersion=${OPENSHIFT_ISTIO_VERSION}"
            - "--deploymentType=${OPENSHIFT_DEPLOYMENT_TYPE}"
            imagePullPolicy: IfNotPresent
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: OPERATOR_NAME
                value: "istio-operator"
```

Cr.yaml
```
apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: true
    community: false
    prefix: openshift-istio-tech-preview/
    version: 0.8.0
  jaeger:
    prefix: distributed-tracing-tech-preview/
    version: 1.9.0
    elasticsearch_memory: 1Gi
  kiali:
    username: username
    password: password
    prefix: kiali/
    version: v0.14.0
```

**Comment by scouturier** [comment]
> Hi @scollier. How did you create this cluster? Did you use oc cluster up? If not, what does your cr.yaml look like?

**Comment by scouturier** [comment]
Also: 0.7.0 works fine with the same templates with version changes

**Comment by knrc** [comment]
@scouturier The product containers have not yet been pushed to the public registry, that is underway but as this is Friday may not be done until Monday.  For now please use the istio_community_operator_template.

**Comment by karimbzu** [comment]
> @scouturier The product containers have not yet been pushed to the public registry, that is underway but as this is Friday may not be done until Monday. For now please use the istio_community_operator_template.

I am facing the same problem in community version, 

Failed to pull image "openshift-istio-tech-preview/openshift-ansible:0.9.0": rpc error: code = Unknown desc = repository docker.io/openshift-istio-tech-preview/openshift-ansible not found: does not exist or no pull access

today i saw the website (https://maistra.io/) is also changed, i thought the problem will be solved but still same problem.

any idea?

**Comment by brian-avery** [comment]
HI Karimbzu, 

Openshift-istio-tech-preview, is product and not community. If you want to use community, can you try the following yaml and let me know if that works? 

```yaml
apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
```

If not, can you please confirm that you have registry.access.redhat.com in your docker registries? I just tested and can download the image from registry.access.redhat.com.

**Comment by karimbzu** [comment]
Hi, brian-avery,
Thanks for your prompt response.
I have tried the yaml file you give for basic configuration, however, still I am unable to deploy.
The attachment is the screenshot of my openshift cluster (3.11 OKD) web console, showing all the pods are either terminating or error status.
 
![basic_installation_output](https://user-images.githubusercontent.com/34478122/54763879-b678f680-4c31-11e9-88a6-60a17bb1af42.png)
Yes you are right, i am unable to access registry.access.redhat.com as i am using Centos OS, below is the output:

[root@master certs.d]# docker login registry.access.redhat.com
Username: drkarim
Password:
Error response from daemon: open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory

Can you guide me how can i get access to registry.access.redhat.com while working on Centos, BTW, i can login through website: https://access.redhat.com/containers/

Kindly help me in to deploy Istio on my OKD 3.11 with all features.
Many thanks

**Comment by brian-avery** [comment]
Hi karimbzu,

Sorry, didn't realize you were trying to run on top of CentOS/OKD. If that's the case, you should use the community images.  What errors are you experiencing when you try to use the yaml I sent you?

Thanks,
Brian

**Comment by karimbzu** [comment]
> Hi karimbzu,
> 
> Sorry, didn't realize you were trying to run on top of CentOS/OKD. If that's the case, you should use the community images. What errors are you experiencing when you try to use the yaml I sent you?
> 
> Thanks,
> Brian

Yes i am using community guideline to configure istio on OKD by the following guideline:
https://maistra.io/docs/getting_started/install/

The yaml file given by you, was successfully deployed but the pods are not running.

[root@master]# oc get pods -n istio-system
NAME                                          READY     STATUS        RESTARTS   AGE
istio-galley-6ff54d9586-6n7vs                 1/1       Terminating   0          1h
istio-sidecar-injector-6f696b8495-s8zrn       1/1       Terminating   0          1h
openshift-ansible-istio-installer-job-bd7kq   0/1       Error         0          1h
openshift-ansible-istio-installer-job-d6n6b   0/1       Error         0          1h
openshift-ansible-istio-installer-job-ts2nj   0/1       Error         0          1h
openshift-ansible-istio-installer-job-tv4ht   1/1       Running       0          1h
prometheus-75b849445c-7vn57                   0/1       Terminating   6          1h

**Comment by brian-avery** [comment]
Hi @karimbzu 

If you do an oc logs -f on the openshift-ansible-istio-installer-job, what do you get? 

Thanks,
Brian

**Comment by karimbzu** [comment]
Hi @brian-avery 
Thanks for your valuable support. I have successfully deployed Istio (community version) on openshift 3.11. Actually, I was mixing community version with product version therefore, getting some errors.
Anyways thanks for your support.

**Comment by brian-avery** [comment]
You're welcome. Glad you got it working.

**Comment by karimbzu** [comment]
thanks Dear @brian-avery 
Apart from all running components, I am facing one issue recently. the sidecar injector pod is not working and giving me error: **"Error: failed to start patch cert loop mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found"**.
_I really appreciate your kind advice._ Thanks

**Comment by brian-avery** [comment]
@karimbzu Are you referring to https://github.com/Maistra/istio/issues/5? If so, can we track in that issue? If not, can you create one? This issue (84) is already closed and a separate issue than the one you're describing.

**Comment by timuluvus** [comment]
I have the same issue as above. I can deploy OK using the code:
```
apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
```
However, this does not install some of the additional components such as Kiali and launcher etc..
But if I use the example yaml :
```
apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: true
    community: false
    prefix: openshift-istio-tech-preview/
    version: 0.9.0
  jaeger:
    prefix: distributed-tracing-tech-preview/
    version: 1.11.0
    elasticsearch_memory: 1Gi
  kiali:
    prefix: openshift-istio-tech-preview/
    version: 0.15.0
    username: username
    password: password
  launcher:
    openshift:
      user: user
      password: password
    github:
      username: username
      token: token
    catalog:
      filter: booster.mission.metadata.istio
      branch: v85
      repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git
  threeScale:
    enabled: false
    prefix: openshift-istio-tech-preview/
    version: 0.4.1
    adapter:
      listenAddr: 3333
      logLevel: info
      logJSON: true
      reportMetrics: true
      metricsPort: 8080
      cacheTTLSeconds: 300
      cacheRefreshSeconds: 180
      cacheEntriesMax: 1000
      cacheRefreshRetries: 1
      allowInsecureConn: false
      clientTimeoutSeconds: 10
```
I get : 
Failed to pull image "openshift-istio-tech-preview/origin-ansible:0.9.0": rpc error: code = Unknown desc = repository docker.io/openshift-istio-tech-preview/origin-ansible not found: does not exist or no pull access

Do I need to change the repository?
